### PR TITLE
findAll deserialize twice

### PR DESCRIPTION
**Pull request by sbounmy**
This PR aim to fix an issue with deserialize called multiple times when finding many records regarding this issue https://github.com/genkgo/ember-localforage-adapter/issues/14

I am able to reproduce the issue in the testing suite.

### CODE REVIEW

**Comment by frederikbosch** [comment]
Looks good. As soon travis thinks it is alright, it will be merged. Seems there is a temporary problem with bower.

**Comment by frederikbosch** [comment]
@sbounmy thanks for your contribution!

**Comment by sbounmy** [comment]
Thank you for merging! would be great to release a 0.6.7 so I can fix this out :) ! thanks

**Comment by frederikbosch** [comment]
Will do as soon as I am behind a computer. I merged from my phone.

**Comment by frederikbosch** [comment]
@sbounmy Done!

**Comment by sbounmy** [comment]
thanks! I'm using ember addon seems like its not available due to some caching
```version not found: ember-localforage-adapter@0.6.7```
Will wait a bit ;)

**Pull request merged**
